// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_MONSTER_MYGAME_SAMPLE_H_
#define FLATBUFFERS_GENERATED_MONSTER_MYGAME_SAMPLE_H_

#include "flatbuffers/flatbuffers.h"


namespace MyGame {
namespace Sample {

struct Vec2;
struct Vec3;
struct Monster;

UENUM(BlueprintType)
enum Color {
  Color_Red = 0,
  Color_Green = 1,
  Color_Blue = 2
};

inline const char **EnumNamesColor() {
  static const char *names[] = { "Red", "Green", "Blue", nullptr };
  return names;
}

inline const char *EnumNameColor(Color e) { return EnumNamesColor()[static_cast<int>(e)]; }

UENUM(BlueprintType)
enum Any {
  Any_NONE = 0,
  Any_Monster = 1
};

inline const char **EnumNamesAny() {
  static const char *names[] = { "NONE", "Monster", nullptr };
  return names;
}

inline const char *EnumNameAny(Any e) { return EnumNamesAny()[static_cast<int>(e)]; }

inline bool VerifyAny(flatbuffers::Verifier &verifier, const void *union_obj, Any type);

MANUALLY_ALIGNED_STRUCT(4) Vec2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  Vec2(float x, float y)
    : x_(flatbuffers::EndianScalar(x)), y_(flatbuffers::EndianScalar(y)) { }

  float x() const { return flatbuffers::EndianScalar(x_); }
  float y() const { return flatbuffers::EndianScalar(y_); }
};
STRUCT_END(Vec2, 8);

MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  Vec2 xy_;
  float z_;

 public:
  Vec3(const Vec2 &xy, float z)
    : xy_(xy), z_(flatbuffers::EndianScalar(z)) { }

  const Vec2 &xy() const { return xy_; }
  float z() const { return flatbuffers::EndianScalar(z_); }
};
STRUCT_END(Vec3, 12);

struct Monster FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  const Vec3 *pos() const { return GetStruct<const Vec3 *>(4); }
  int32_t mana() const { return GetField<int32_t>(6, 150); }
  int32_t hp() const { return GetField<int32_t>(8, 100); }
  const flatbuffers::String *name() const { return GetPointer<const flatbuffers::String *>(10); }
  const flatbuffers::Vector<uint8_t> *inventory() const { return GetPointer<const flatbuffers::Vector<uint8_t> *>(12); }
  const flatbuffers::Vector<flatbuffers::Offset<Monster>> *vtable() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<Monster>> *>(14); }
  const flatbuffers::Vector<const Vec3 *> *vstruct() const { return GetPointer<const flatbuffers::Vector<const Vec3 *> *>(16); }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *vstring() const { return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(18); }
  const flatbuffers::Vector<int8_t> *venum() const { return GetPointer<const flatbuffers::Vector<int8_t> *>(20); }
  const Monster *frenemy() const { return GetPointer<const Monster *>(22); }
  Color color() const { return static_cast<Color>(GetField<int8_t>(24, 2)); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Vec3>(verifier, 4 /* pos */) &&
           VerifyField<int32_t>(verifier, 6 /* mana */) &&
           VerifyField<int32_t>(verifier, 8 /* hp */) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 10 /* name */) &&
           verifier.Verify(name()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 12 /* inventory */) &&
           verifier.Verify(inventory()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 14 /* vtable */) &&
           verifier.Verify(vtable()) &&
           verifier.VerifyVectorOfTables(vtable()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 16 /* vstruct */) &&
           verifier.Verify(vstruct()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 18 /* vstring */) &&
           verifier.Verify(vstring()) &&
           verifier.VerifyVectorOfStrings(vstring()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 20 /* venum */) &&
           verifier.Verify(venum()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 22 /* frenemy */) &&
           verifier.VerifyTable(frenemy()) &&
           VerifyField<int8_t>(verifier, 24 /* color */) &&
           verifier.EndTable();
  }
};

struct MonsterBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_pos(const Vec3 *pos) { fbb_.AddStruct(4, pos); }
  void add_mana(int32_t mana) { fbb_.AddElement<int32_t>(6, mana, 150); }
  void add_hp(int32_t hp) { fbb_.AddElement<int32_t>(8, hp, 100); }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) { fbb_.AddOffset(10, name); }
  void add_inventory(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> inventory) { fbb_.AddOffset(12, inventory); }
  void add_vtable(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Monster>>> vtable) { fbb_.AddOffset(14, vtable); }
  void add_vstruct(flatbuffers::Offset<flatbuffers::Vector<const Vec3 *>> vstruct) { fbb_.AddOffset(16, vstruct); }
  void add_vstring(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> vstring) { fbb_.AddOffset(18, vstring); }
  void add_venum(flatbuffers::Offset<flatbuffers::Vector<int8_t>> venum) { fbb_.AddOffset(20, venum); }
  void add_frenemy(flatbuffers::Offset<Monster> frenemy) { fbb_.AddOffset(22, frenemy); }
  void add_color(Color color) { fbb_.AddElement<int8_t>(24, static_cast<int8_t>(color), 2); }
  MonsterBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  MonsterBuilder &operator=(const MonsterBuilder &);
  flatbuffers::Offset<Monster> Finish() {
    auto o = flatbuffers::Offset<Monster>(fbb_.EndTable(start_, 11));
    return o;
  }
};

inline flatbuffers::Offset<Monster> CreateMonster(flatbuffers::FlatBufferBuilder &_fbb,
   const Vec3 *pos = 0,
   int32_t mana = 150,
   int32_t hp = 100,
   flatbuffers::Offset<flatbuffers::String> name = 0,
   flatbuffers::Offset<flatbuffers::Vector<uint8_t>> inventory = 0,
   flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Monster>>> vtable = 0,
   flatbuffers::Offset<flatbuffers::Vector<const Vec3 *>> vstruct = 0,
   flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> vstring = 0,
   flatbuffers::Offset<flatbuffers::Vector<int8_t>> venum = 0,
   flatbuffers::Offset<Monster> frenemy = 0,
   Color color = Color_Blue) {
  MonsterBuilder builder_(_fbb);
  builder_.add_frenemy(frenemy);
  builder_.add_venum(venum);
  builder_.add_vstring(vstring);
  builder_.add_vstruct(vstruct);
  builder_.add_vtable(vtable);
  builder_.add_inventory(inventory);
  builder_.add_name(name);
  builder_.add_hp(hp);
  builder_.add_mana(mana);
  builder_.add_pos(pos);
  builder_.add_color(color);
  return builder_.Finish();
}

inline bool VerifyAny(flatbuffers::Verifier &verifier, const void *union_obj, Any type) {
  switch (type) {
    case Any_NONE: return true;
    case Any_Monster: return verifier.VerifyTable(reinterpret_cast<const Monster *>(union_obj));
    default: return false;
  }
}

inline const MyGame::Sample::Monster *GetMonster(const void *buf) { return flatbuffers::GetRoot<MyGame::Sample::Monster>(buf); }

inline bool VerifyMonsterBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<MyGame::Sample::Monster>(); }

inline void FinishMonsterBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<MyGame::Sample::Monster> root) { fbb.Finish(root); }

}  // namespace Sample
}  // namespace MyGame

#endif  // FLATBUFFERS_GENERATED_MONSTER_MYGAME_SAMPLE_H_
